### ISSUE TITLE
How to extend localStorage.getItem?

### ISSUE THREAD

**Issue by rickysullivan** [clarkbw/jest-localstorage-mock#122]
The project I'm working on has extended the default `localStorage.getItem` method to return a fallback value (if set) if the item is undefined/null.  

```
/**
 * Get an item from localStorage
 * @param {String} key - the key of the value
 * @param {*} fallbackValue - the fallback value in case the item cannot be retrieved
 */
export const getItem = (key, fallbackValue) => {
    let item;

    if (hasLocalStorage()) {
        item = localstorage.getItem(key);
    }

    if ((typeof item === 'undefined' || item === null) && typeof fallbackValue !== 'undefined') {
        return fallbackValue;
    }

    return item;
};
```

How would I extend the mock `getItem` method to match?

I'm currently using the function like this: `const getItem = jest.fn(localStorage.getItem);`

**Comment by clarkbw** [comment]
I'd probably overwrite it.

```javascript
const old = localStorage.getItem
localStorage.getItem = jest.fn((key, default) => old(key) || default)
```

**Comment by rickysullivan** [comment]
`Cannot assign to read only property 'getItem' of object '[object Object]'`. 

I assume this is because `getItem` isn't writable?
