### ISSUE TITLE
The `undefined` value is inconsistent with the browser

### ISSUE THREAD

**Issue by vst-h** [clarkbw/jest-localstorage-mock#142]
```js
localStorage.setItem("k", undefined)
let val1 = localStorage.getItem("k") 
console.log(val1) // val1 === null , browser:  val1 === "undefined"
console.log(localStorage) // LocalStorage { k: '' }
```
The above code `val1 === null`, by logging localStorage, the value of `k` is `''`. 
Check the code the problem should be here: [code](https://github.com/clarkbw/jest-localstorage-mock/blob/master/src/localstorage.js#L10). `(key, val = '') => `, the `val` parameter should not have a default value.

**Comment by clarkbw** [comment]
If you can write a test for this and update that code I believe you've identified the issue.  I don't recall why there is a default value for that.

It didn't [start with a default value](https://github.com/clarkbw/jest-localstorage-mock/blame/4a47db3ee0d8ebd528edbc0af8aa88f81e4f7877/src/localstorage.js#L14) but when the issue of [returning a string value](https://github.com/clarkbw/jest-localstorage-mock/blame/2a247c20818abbe3c33bfdae2afba1c0854705ec/src/localstorage.js#L14) came up the default value changed.  [PR](https://github.com/clarkbw/jest-localstorage-mock/pull/37) and [Issue](https://github.com/clarkbw/jest-localstorage-mock/issues/35)
