### ISSUE TITLE
Add 2.0.0 changelog/migration notes

### ISSUE THREAD

**Issue by samsch** [clarkbw/jest-localstorage-mock#33]
A quick look through the repo didn't make it clear what changed from version <2.0.0 to 2.0.0, and whether the assumed BC break would affect (my) use of the module.

Maybe the 2.0.0 release could be updated with a short blurb about the upgrade?

**Comment by clarkbw** [comment]
Ok, I've written up a quick set of release notes here: https://github.com/clarkbw/jest-localstorage-mock/releases/tag/v2.0.0
