### ISSUE TITLE
Can I mock this only in a certain describe or test file? 

### ISSUE THREAD

**Issue by Haroenv** [clarkbw/jest-localstorage-mock#43]
Hey!

This package seems great, I'm currently manually mocking it, but it doesn't seem great. I'd love to test the behaviour when localStorage is available and when it isn't available. 

I'm writing my test like this currently: https://github.com/algolia/algoliasearch-client-javascript/blob/feat/v4-for-real-now/packages/universal-store/index.test.js#L41-L54

**Comment by clarkbw** [comment]
Good question!  👏 

I might try clobbering the global.  Perhaps doing something like this:

```js
let localLocalStorage = global.localStorage;
global.localStorage = undefined;
// test for when there isn't localStorage available
// and you could reset it like this
global.localStorage = localLocalStorage;
```
I believe each test file will reset the global variables anyway so if you clobbered in a single file you wouldn't have to set it back up.

Let me know how this works!  And I'd appreciate if you could update the [README](../blob/master/README.md) with what you've found working. 🙇

**Comment by Haroenv** [comment]
Cool, I went the opposite direction (localStorage normally isn't available, also test the case where it exists), but explicitly setting it as undefined in some cases will probably work, since that's what I'm testing for in application code. 

I'll let you know if I decide to move away from my from-scratch localstorage solution to yours

**Comment by clarkbw** [comment]
OIC

If you just wanted to turn this on in certain places I believe you could forgo the setup files config and instead just require it as needed.

Add this to the top of the tests where you want it.
```
require("jest-localstorage-mock");
```

**Comment by Haroenv** [comment]
Right, that works ❤️
