### ISSUE TITLE
reset jest mock functions

### ISSUE THREAD

**Issue by Aligertor** [clarkbw/jest-localstorage-mock#44]
I cannot run multiple tests without beeing sure that the evaluateing the jest.fn()´s are actually called only from the current test.

for example test like this will pass when run together but the second test will fail when run allone
```js
test('should save to localStorage', () => {
  const KEY = 'foo', VALUE = 'bar';
  dispatch(action.update(KEY, VALUE));
  expect(localStorage.setItem).toHaveBeenCalledTimes(1);
});

test('should save to localStorage again', () => {
  const KEY = 'fooo', VALUE = 'barr';
  dispatch(action.update(KEY, VALUE));
  expect(localStorage.setItem).toHaveBeenCalledTimes(2);
});
```

there should be a way to reinitalize the mock functions in a beforeEach block so i can be sure that their calls are only from the current test and or related beforeEach blocks.

**Comment by clarkbw** [comment]
You should be able to use [jest.resetAllMocks()](http://facebook.github.io/jest/docs/en/jest-object.html#jestresetallmocks) and / or [mockFn.mockReset()](https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockreset)

Like so:

```js
beforeEach(() => {
  // reset all mocks, which could impact your other mocks
  jest.resetAllMocks();
  // or individually
  localStorage.setItem.mockReset();
  // note that values stored will also be available in other tests you may also want
  localStorage.clear();
});

test('should save to localStorage', () => {
  const KEY = 'foo', VALUE = 'bar';
  dispatch(action.update(KEY, VALUE));
  expect(localStorage.setItem).toHaveBeenCalledTimes(1);
  // or after each use
  localStorage.setItem.mockReset();
  localStorage.clear();
});

test('should save to localStorage again', () => {
  const KEY = 'fooo', VALUE = 'barr';
  dispatch(action.update(KEY, VALUE));
  expect(localStorage.setItem).toHaveBeenCalledTimes(2);
});
```

If this answers your question, could you create a pull request to add this to the README? thx

**Comment by iprignano** [comment]
I think what you want here is [`mockClear()`](https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockclear) rather than `mockReset()`. The latter will completely wipe the mock implementation.

**Comment by clarkbw** [comment]
Thanks @iprignano I'll fix up the comment to use clear instead.
