### ISSUE TITLE
How do I make API methods throw an exception

### ISSUE THREAD

**Issue by dentuzhik** [clarkbw/jest-localstorage-mock#65]
Here's a checklist you can use to make sure your issue can be more easily resolved:

- [x] Check against the [latest](https://github.com/clarkbw/jest-localstorage-mock/releases/latest)
- [x] Include a link to the example application source code

I am trying to write a test, which assumes that sometimes `getItem` or `setItem` throw, this can happen f.e. if you are browser LS is running out of space.

What I've tried:
- `localStorage.setItem.mockImplementation(() => { throw new Error('error') })`
- `jest.spyOn(localStorage, 'setItem').mockImplementation(() => { throw new Error('error') })`

Both examples work, however I cannot restore mocks to original behaviour defined in the library, I've tried:
- `jest.resetAllMocks` or `localStorage.setItem.mockReset` for 1st example
- `jest.restoreAllMocks` or `localStorage.setItem.mockRestore` for 2nd example

Am I missing something obvious or is it methods defined through `defineProperty` prevents me from doing this?

**Comment by clarkbw** [comment]
I would have thought the first approach with `mockReset` would have worked. 🤔

**Comment by dentuzhik** [comment]
In a way it does, it just doesn't work properly after reset. I submitted failed test.

**Comment by evocateur** [comment]
`localStorage.setItem.mockImplementationOnce(() => { throw new Error('error'); });` should work, I think? `mockImplementationOnce` doesn't replace the default `jest.fn(impl)` (which is effectively an [alias](https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockimplementationfn) for `jest.fn().mockImplementation(impl)`), and automatically clears itself from the mock when triggered, thus preserving the default implementation for other tests.

**Comment by clarkbw** [comment]
☝️ seems to work for me, closing this out.
