### ISSUE TITLE
getItem() bug

### ISSUE THREAD

**Issue by Katarn** [clarkbw/jest-localstorage-mock#74]
I seem to have found the wrong work of `getItem()` method. Try this code in browser console and mock:

```js
localStorage.setItem("param", 1);

typeof JSON.parse(localStorage.getItem("param")); // "number" in Chrome and "string" in this mock
```

It not bug in `JSON.parse()` method because I also tested `typeof JSON.parse("1")` in Node and it was `"number"`.

**Comment by clarkbw** [comment]
This likely comes from out `setItem` method that appends a string. https://github.com/clarkbw/jest-localstorage-mock/blob/master/src/localstorage.js

**Comment by Katarn** [comment]
But `typeof JSON.parse("1")` returns `number`. Moreover argument of this method - string.
