### ISSUE TITLE
"jest.resetAllMocks();" does not work

### ISSUE THREAD

**Issue by Oliboy50** [clarkbw/jest-localstorage-mock#83]
<img width="668" alt="capture d ecran 2018-08-22 a 16 28 23" src="https://user-images.githubusercontent.com/2571084/44469726-6d73ac00-a628-11e8-9caa-1aa184ea6141.png">

in the README, you say that `jest.resetAllMocks` works, but it does not, if I use it, the `__STORE__` is always empty even if I `setItem()` in my tests

`localStorage.clear();` for instance works as expected

but when I use `jest.resetAllMocks` (to clear other mocks of my test) in combination to `localStorage.clear();`, it does not work anymore

I'm running `jest` v23.4.2

**Comment by clarkbw** [comment]
Can you link to the code you're using?  I don't have enough context from this to understand the problem.

**Comment by Oliboy50** [comment]
for instance, you could add a test in this project and try to use `jest.resetAllMocks` yourself to check if it really does work

> if I use it, the __STORE__ is always empty even if I setItem() in my tests

**Comment by clarkbw** [comment]
> you could add a test in this project and try to use `jest.resetAllMocks` yourself to check if it really does work

I'll try to take a look.  Feel free to create a PR that fails this way.

**Comment by daniellizik** [comment]
I had this issue as well but as per [this line](https://github.com/clarkbw/jest-localstorage-mock/blob/master/__tests__/index.js#L6) I guess `.clearAllMocks()` is the correct method to use ([reference](https://jestjs.io/docs/en/jest-object#jestclearallmocks))

**Comment by daniula** [comment]
`jest.resetAllMocks` clears `jest.fn()` mocked implementations. Because of that all `jest.fn()` used in [`localstorage.js`](https://github.com/clarkbw/jest-localstorage-mock/blob/master/src/localstorage.js#L5) will start returning `undefined`. This is especially annoying if you enable [`resetMocks`](https://jestjs.io/docs/en/configuration.html#resetmocks-boolean) in jest config.

**Comment by AOEChamp** [comment]
Thanks @daniellizik  that worked for me.

More specifically, `resetAllMocks` breaks the mocks. `clearAllMocks` clears the mocks (call count, etc) but does not clear the storage. I had to use it in conjunction with `localStorage.clear()` to fully reset the state between tests.

I'm surprised this has been open for years now, when all that needs to be done is to update the documentation.
