### ISSUE TITLE
cannot set localStorage.__STORE__ to an empty object

### ISSUE THREAD

**Issue by iyunusov** [clarkbw/jest-localstorage-mock#90]
when this is used `localStorage.__STORE__ = {};` console returns:
`TypeError: Cannot set property __STORE__ of #<LocalStorage> which has only a getter
`

**Comment by clarkbw** [comment]
Yeah, only a getter 

https://github.com/clarkbw/jest-localstorage-mock/blob/master/src/localstorage.js#L42-L44

You want to use the `clear` function https://github.com/clarkbw/jest-localstorage-mock/blob/master/src/localstorage.js#L20 instead

**Comment by jorahood** [comment]
You should update the README as it still mentions this:
```
// or directly reset the storage
  localStorage.__STORE__ = {};
```
